### ISSUE TITLE
wx version?

### ISSUE THREAD

**Issue by samhiatt** [scjurgen/hpd-20#1]
What wx version are you using? Could you add some documentation on where to find the source code? pip install wx fails for me, not finding any packages that match (for OS X). I tried pip install wxPython, which installed wx, but it appears to be an incompatible version.

**Comment by scjurgen** [comment]
Hi Sam, I installed wxpython by using homebrew. And the version installed is 3.0.2.0.
I have been thinking about using tkinter. I will have a look into compatibility on other systems.

**Comment by scjurgen** [comment]
I made a fix for the pip installed version. Use pip to force the latest version (0.0.9). Let me know if it works for you.

**Comment by samhiatt** [comment]
Awesome! I'll give it a try and let you know. 

I'm excited to see how this works. Was going to try loading some samples to my handsonic today anyway, so it will be great to give this a try again. Thanks man!

**Comment by samhiatt** [comment]
Sweet, I got it working!

Running OS X El Cap (10.11.6), Anaconda python 2.7.11, and Homebrew, I had to do the following to install and run:
```
brew install wxpython
pip install wxPython
```

Then running /anaconda/bin/hpd20-ui still failed, saying
> This program needs access to the screen. Please run with a Framework build of python, and only when you are logged in on the main display of your Mac.  

But running with pythonw worked.
```
/anaconda/bin/pythonw /anaconda/bin/hpd20-ui
```

Yay!   

Man, this is really cool! It's so nice to have this view of all the sets loaded. And the work you've done with the scales is really interesting. I've been playing with some obscure scales on my Ableton Push and think it will be nice to easily load the ones I like onto the Handsonic now.

Hey, do you work with Ableton? I'm curious if you've done any work to set up any software instruments that respond to HPD-20's MIDI signals. That's been something I've been wanting to do for a while now.
